-- Farmingdale's pickup and delivery catering catalog, transcribed from the
-- store's catering ordering screens. Prices are stored as integer cents so a
-- catalog edit can never introduce floating-point rounding into order records.

alter table public.catering_menu_items
  add column if not exists pickup_price_cents integer,
  add column if not exists delivery_price_cents integer;

alter table public.catering_menu_items
  add constraint catering_menu_items_pickup_price_cents_check
    check (pickup_price_cents is null or pickup_price_cents >= 0),
  add constraint catering_menu_items_delivery_price_cents_check
    check (delivery_price_cents is null or delivery_price_cents >= 0);

create unique index if not exists catering_menu_items_name_unique
  on public.catering_menu_items (name);

with catalog(name, category, pickup_price_cents, delivery_price_cents) as (
  values
    ('Small Chick-fil-A Chick-n-Minis Tray', 'Breakfast', 2650, 3450),
    ('Large Chick-fil-A Chick-n-Minis Tray', 'Breakfast', 5000, 6600),
    ('10 ct Chick-fil-A Chick-n-Minis Tray-Shaped Tray', 'Breakfast', null, 799),
    ('Chick-fil-A Chicken Biscuit', 'Breakfast', 439, 569),
    ('Spicy Chicken Biscuit', 'Breakfast', 465, 465),
    ('Bacon Biscuit', 'Breakfast', 375, 489),
    ('Sausage Biscuit', 'Breakfast', 375, 489),
    ('Buttery Biscuit', 'Breakfast', 189, 245),
    ('Berry Parfait w/ Cookie Crumbs', 'Breakfast', 529, 689),
    ('Berry Parfait w/ Granola', 'Breakfast', 529, 689),
    ('Small Fruit Cup', 'Breakfast', 359, 465),
    ('Medium Fruit Cup', 'Breakfast', 475, 619),
    ('Large Fruit Cup', 'Breakfast', 679, 879),
    ('Grilled Chicken Bundle', 'Trays', 8950, 11650),
    ('Small Hot Chick-fil-A Nuggets Tray', 'Trays', 4350, 5650),
    ('Medium Hot Chick-fil-A Nuggets Tray', 'Trays', 8100, 10550),
    ('Large Hot Chick-fil-A Nuggets Tray', 'Trays', 12900, 16750),
    ('Small Chilled Chick-fil-A Nuggets Tray', 'Trays', 4350, 5650),
    ('Medium Chilled Chick-fil-A Nuggets Tray', 'Trays', 8100, 10550),
    ('Large Chilled Chick-fil-A Nuggets Tray', 'Trays', 12900, 16750),
    ('Small Hot Chick-n-Strips Tray', 'Trays', 4350, 5650),
    ('Medium Hot Chick-n-Strips Tray', 'Trays', 8100, 10550),
    ('Large Hot Chick-n-Strips Tray', 'Trays', 12900, 16750),
    ('Small Chilled Chick-n-Strips (Cooked & Chilled for Later) Tray', 'Trays', 4350, 5650),
    ('Medium Chilled Chick-n-Strips (Cooked & Chilled for Later) Tray', 'Trays', 8100, 10550),
    ('Large Chilled Chick-n-Strips (Cooked & Chilled for Later) Tray', 'Trays', 12900, 16750),
    ('Small Chilled Grilled Chicken Sub Sandwich Tray', 'Trays', 3250, 4200),
    ('Medium Chilled Grilled Chicken Sub Sandwich Tray', 'Trays', 5450, 7100),
    ('Large Chilled Grilled Chicken Sub Sandwich Tray', 'Trays', 6750, 8750),
    ('Small Spicy Chilled Grilled Chicken Sub Sandwich Tray', 'Trays', 3250, 4200),
    ('Medium Spicy Chilled Grilled Chicken Sub Sandwich Tray', 'Trays', 5450, 7100),
    ('Large Spicy Chilled Grilled Chicken Sub Sandwich Tray', 'Trays', 6750, 8750),
    ('Small Chick-fil-A Cool Wrap Tray', 'Trays', 3100, 4050),
    ('Medium Chick-fil-A Cool Wrap Tray', 'Trays', 5100, 6650),
    ('Large Chick-fil-A Cool Wrap Tray', 'Trays', 6400, 8300),
    ('Small Southwest Veggie Wrap Tray', 'Trays', 2950, 3950),
    ('Medium Southwest Veggie Wrap Tray', 'Trays', 4850, 6300),
    ('Large Southwest Veggie Wrap Tray', 'Trays', 6050, 7850),
    ('Small Spicy Cool Wrap Tray', 'Trays', 3100, 4050),
    ('Medium Spicy Cool Wrap Tray', 'Trays', 5100, 6650),
    ('Large Spicy Cool Wrap Tray', 'Trays', 6400, 8300),
    ('Small Fruit Tray', 'Trays', 4000, 5200),
    ('Large Fruit Tray', 'Trays', 8000, 10400),
    ('Small Mac & Cheese Tray', 'Trays', 4300, 5650),
    ('Large Mac & Cheese Tray', 'Trays', 8200, 10650),
    ('Small Garden Salad Tray', 'Trays', 2200, 2850),
    ('Large Garden Salad Tray', 'Trays', 4300, 5600),
    ('Small Kale Crunch Side Tray', 'Trays', 2600, 3400),
    ('Large Kale Crunch Side Tray', 'Trays', 5100, 6650),
    ('Small Chocolate Chunk Cookie Tray', 'Trays', 2300, 3000),
    ('Large Chocolate Chunk Cookie Tray', 'Trays', 4400, 5750),
    ('Small Chocolate Fudge Brownie Tray', 'Trays', 1500, 1950),
    ('Large Chocolate Fudge Brownie Tray', 'Trays', 2900, 3750),
    ('Small Chocolate Chunk Cookie and Chocolate Fudge Brownie Tray', 'Trays', 1750, 2250),
    ('Large Chocolate Chunk Cookie and Chocolate Fudge Brownie Tray', 'Trays', 3500, 4550),
    ('Regular Chick-fil-A Chicken Sandwich Packaged Meal', 'Packaged Meals', 1177, 1397),
    ('Premium Chick-fil-A Chicken Sandwich Packaged Meal', 'Packaged Meals', 1346, 1746),
    ('Regular Spicy Chicken Sandwich Packaged Meal', 'Packaged Meals', 1117, 1453),
    ('Premium Spicy Chicken Sandwich Packaged Meal', 'Packaged Meals', 1386, 1802),
    ('Regular 8 ct Chick-fil-A Nuggets Packaged Meal', 'Packaged Meals', 1083, 1407),
    ('Premium 8 ct Chick-fil-A Nuggets Packaged Meal', 'Packaged Meals', 1352, 1756),
    ('Regular Chilled Grilled Chicken Sub Packaged Meal', 'Packaged Meals', 1242, 1643),
    ('Premium Chilled Grilled Chicken Sub Packaged Meal', 'Packaged Meals', 1582, 1992),
    ('Regular Spicy Chilled Grilled Chicken Sub Packaged Meal', 'Packaged Meals', 1263, 1643),
    ('Premium Spicy Chilled Grilled Chicken Sub Packaged Meal', 'Packaged Meals', 1532, 1992),
    ('Regular Chick-fil-A Cool Wrap Packaged Meal', 'Packaged Meals', 1407, 1827),
    ('Premium Chick-fil-A Cool Wrap Packaged Meal', 'Packaged Meals', 1676, 2176),
    ('Regular Spicy Cool Wrap Packaged Meal', 'Packaged Meals', 1407, 1827),
    ('Premium Spicy Cool Wrap Packaged Meal', 'Packaged Meals', 1676, 2176),
    ('Regular Southwest Veggie Wrap Packaged Meal', 'Packaged Meals', 1357, 1763),
    ('Premium Southwest Veggie Wrap Packaged Meal', 'Packaged Meals', 1626, 2112),
    ('Chick-fil-A Chicken Sandwich', 'Entrees', 609, 789),
    ('Spicy Chicken Sandwich', 'Entrees', 649, 845),
    ('5 ct Chick-fil-A Nuggets', 'Entrees', 385, 499),
    ('8 ct Chick-fil-A Nuggets', 'Entrees', 615, 799),
    ('12 ct Chick-fil-A Nuggets', 'Entrees', 849, 1105),
    ('Chilled Grilled Chicken Sub Sandwich', 'Entrees', 795, 1035),
    ('Spicy Chilled Grilled Chicken Sub Sandwich', 'Entrees', 795, 1035),
    ('Chick-fil-A Cool Wrap', 'Salads & Wraps', 939, 1219),
    ('Spicy Cool Wrap', 'Salads & Wraps', 939, 1219),
    ('Southwest Veggie Wrap', 'Salads & Wraps', 889, 1155),
    ('Market Salad w/ Grilled Filet (Cold)', 'Salads & Wraps', 1059, 1375),
    ('Market Salad w/ Spicy Grilled Filet (Cold)', 'Salads & Wraps', 1059, 1375),
    ('Market Salad w/ No Chicken', 'Salads & Wraps', 815, 1058),
    ('Cobb Salad w/ Grilled Filet (Cold)', 'Salads & Wraps', 1039, 1349),
    ('Cobb Salad w/ Spicy Grilled Filet (Cold)', 'Salads & Wraps', 1039, 1349),
    ('Cobb Salad w/ No Chicken', 'Salads & Wraps', 795, 1035),
    ('Spicy Southwest Salad w/ Spicy Grilled Filet (Cold)', 'Salads & Wraps', 1059, 1375),
    ('Spicy Southwest Salad w/ No Chicken', 'Salads & Wraps', 815, 1059),
    ('Kale Crunch Side', 'Sides & Treats', 475, 619),
    ('Side Salad', 'Sides & Treats', 475, 619),
    ('Original Flavor Waffle Potato Chips', 'Sides & Treats', 269, 349),
    ('Chick-fil-A Sauce Flavored Waffle Potato Chips', 'Sides & Treats', 269, 349),
    ('Chocolate Chunk Cookie', 'Sides & Treats', 199, 259),
    ('6 pack Chocolate Chunk Cookie', 'Sides & Treats', 1125, 1465),
    ('Chocolate Fudge Brownie', 'Sides & Treats', 249, 325),
    ('Gallon Pineapple Dragonfruit Lemonade', 'Beverages', 1575, 2050),
    ('Gallon Pineapple Dragonfruit Diet Lemonade', 'Beverages', 1575, 2050),
    ('Gallon Pineapple Dragonfruit Sunjoy (1/2 Sweet Tea, 1/2 Lemonade)', 'Beverages', 1400, 1825),
    ('Gallon Pineapple Dragonfruit Sunjoy (1/2 Unsweet Tea, 1/2 Lemonade)', 'Beverages', 1400, 1825),
    ('Gallon Pineapple Dragonfruit Sunjoy (1/2 Sweet Tea, 1/2 Diet Lemonade)', 'Beverages', 1400, 1825),
    ('Gallon Pineapple Dragonfruit Sunjoy (1/2 Unsweet Tea, 1/2 Diet Lemonade)', 'Beverages', 1400, 1825),
    ('Gallon Pineapple Dragonfruit Sweet Tea', 'Beverages', 1000, 1300),
    ('Gallon Pineapple Dragonfruit Unsweet Tea', 'Beverages', 1000, 1300),
    ('Gallon Freshly-Brewed Iced Tea Sweetened', 'Beverages', 700, 900),
    ('Gallon Freshly-Brewed Iced Tea Unsweetened', 'Beverages', 700, 900),
    ('Gallon Chick-fil-A Iced Tea (1/2 Sweet Tea, 1/2 Unsweet Tea)', 'Beverages', 700, 900),
    ('Gallon Chick-fil-A Lemonade', 'Beverages', 1275, 1650),
    ('Gallon Chick-fil-A Diet Lemonade', 'Beverages', 1275, 1650),
    ('Gallon Chick-fil-A Lemonade (1/2 Lemonade, 1/2 Diet Lemonade)', 'Beverages', 1275, 1650),
    ('Gallon Sunjoy (1/2 Sweet Tea, 1/2 Lemonade)', 'Beverages', 1100, 1425),
    ('Gallon Sunjoy (1/2 Sweet Tea, 1/2 Diet Lemonade)', 'Beverages', 1100, 1425),
    ('Gallon Sunjoy (1/2 Unsweet Tea, 1/2 Lemonade)', 'Beverages', 1100, 1425),
    ('Gallon Sunjoy (1/2 Unsweet Tea, 1/2 Diet Lemonade)', 'Beverages', 1100, 1425),
    ('Bottled Lemonade', 'Beverages', null, 449),
    ('DASANI Bottled Water', 'Beverages', 259, 335),
    ('Simply Orange', 'Beverages', 339, 439),
    ('Honest Kids Apple Juice', 'Beverages', 225, 295),
    ('1% Milk', 'Beverages', 225, 295),
    ('1% Chocolate Milk', 'Beverages', 225, 295),
    ('Bag of Ice', 'Beverages', 300, 300),
    ('Regular 96 oz Coffee', 'Beverages', 1600, 2100),
    ('8 oz Chick-fil-A Sauce', 'Sauces & Dressings', 325, 419),
    ('8 oz Garden Herb Ranch Sauce', 'Sauces & Dressings', 325, 419),
    ('8 oz Polynesian Sauce', 'Sauces & Dressings', 325, 419),
    ('8 oz Honey Mustard Sauce', 'Sauces & Dressings', 325, 419),
    ('8 oz Barbeque Sauce', 'Sauces & Dressings', 325, 419),
    ('BBQ Sauce Packet', 'Sauces & Dressings', null, null),
    ('Buffalo Sauce Packet', 'Sauces & Dressings', null, null),
    ('Chick-fil-A Sauce Packet', 'Sauces & Dressings', null, null),
    ('Honey Roasted BBQ Sauce Packet', 'Sauces & Dressings', null, null),
    ('Honey Mustard Sauce Packet', 'Sauces & Dressings', null, null),
    ('Polynesian Sauce Packet', 'Sauces & Dressings', null, null),
    ('Ranch Sauce Packet', 'Sauces & Dressings', null, null),
    ('Sriracha Sauce Packet', 'Sauces & Dressings', null, null),
    ('Avocado Lime Ranch Dressing', 'Sauces & Dressings', null, null),
    ('Creamy Salsa Dressing', 'Sauces & Dressings', null, null),
    ('Garden Herb Ranch Dressing', 'Sauces & Dressings', null, null),
    ('Honey Mustard Dressing', 'Sauces & Dressings', null, null),
    ('Light Balsamic Vinaigrette Dressing', 'Sauces & Dressings', null, null),
    ('Lite Italian Dressing', 'Sauces & Dressings', null, null),
    ('Zesty Apple Cider Vinaigrette Dressing', 'Sauces & Dressings', null, null),
    ('Grape Jelly', 'Sauces & Dressings', null, null),
    ('Strawberry Jelly', 'Sauces & Dressings', null, null),
    ('Honey Packet', 'Sauces & Dressings', null, null),
    ('Roasted Almonds', 'Sauces & Dressings', null, null)
)
insert into public.catering_menu_items (
  name, category, pickup_price_cents, delivery_price_cents, components, scaling_rules, active
)
select name, category, pickup_price_cents, delivery_price_cents, '[]'::jsonb, '[]'::jsonb, true
from catalog
on conflict (name) do update
set
  category = excluded.category,
  pickup_price_cents = excluded.pickup_price_cents,
  delivery_price_cents = excluded.delivery_price_cents,
  active = true;

-- Retire the original placeholder choices so staff only selects Farmingdale's
-- photographed catalog. Historical order rows continue to retain their link.
update public.catering_menu_items
set active = false
where name in (
  '8-Count Nugget Tray',
  'Chicken Sandwich Boxed Meal',
  '100-Count Nugget Tray',
  'Gallon Beverage',
  'Fruit Tray'
);
